version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: restaurant-app
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=restaurant
      - DB_USER=root
      - DB_PASSWORD=rootpassword
    ports:
      - "8080:8080"
    depends_on:
      - mysql

  mysql:
    build:
      context: ./scripts
      dockerfile: Dockerfile
    container_name: mysql-db
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=restaurant
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
